class SpeedRunLoader : AutoReloader {

	int chugdelay;

	default{
		hdweapon.refid "7sl";
		tag "$TAG_7MMSPEEDLOADER";
		inventory.pickupmessage "$PICKUP_7MMSPEEDLOADER";
	}
	override double weaponbulk(){ return 35*amount; }
	override string,double getpickupsprite(){ return "RLDRB0",1.; }
	override void DrawHUDStuff(HDStatusBar sb,HDWeapon hdw,HDPlayerPawn hpl){
		vector2 bob=hpl.wepbob*0.3;
		int brass=hpl.countinv("SevenMilBrass");
		int fourm=hpl.countinv("FourMilAmmo");
		double lph=(brass&&fourm>=HDCONST_FOURFORSEVEN)?1.:0.6;

		sb.drawimage("RLDRB0",(0,-64)+bob, // literally overriding one sprite here
			sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_ITEM_CENTER,
			alpha:lph,scale:(2,2)
		);

		sb.drawimage("RBRSA3A7",(-30,-64)+bob,
			sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_ITEM_CENTER|sb.DI_ITEM_RIGHT,
			alpha:lph,scale:(2.5,2.5)
		);
		sb.drawimage("RCLSA3A7",(30,-64)+bob,
			sb.DI_SCREEN_CENTER_BOTTOM|sb.DI_ITEM_CENTER|sb.DI_ITEM_LEFT,
			alpha:lph,scale:(1.9,4.7)
		);
		sb.drawstring(
			sb.psmallfont,""..brass,(-30,-54)+bob,
			sb.DI_TEXT_ALIGN_RIGHT|sb.DI_SCREEN_CENTER_BOTTOM,
			fourm?Font.CR_GOLD:Font.CR_DARKGRAY,alpha:lph
		);
		sb.drawstring(
			sb.psmallfont,""..fourm,(30,-54)+bob,
			sb.DI_TEXT_ALIGN_LEFT|sb.DI_SCREEN_CENTER_BOTTOM,
			fourm?Font.CR_LIGHTBLUE:Font.CR_DARKGRAY,alpha:lph
		);
	}
	override string gethelptext(){
		LocalizeHelp();
		return
		LWPHELP_FIRE..StringTable.Localize("$SRLWH_FIRE") // "  Assemble rounds (Stand the hell back)\n"
		..LWPHELP_USE.."+"..LWPHELP_UNLOAD..StringTable.Localize("$ARELWH_SAMELOL") // "  same"
		;
	}
	void A_SpeedMakeRound(){
		if(
			weaponstatus[RELS_BRASS]<1
			||weaponstatus[RELS_POWDER]<HDCONST_FOURFORSEVEN
		){
			makinground=false;
			setstatelabel("spawn");

			//spit out any remaining materials
			if(weaponstatus[RELS_BRASS]>0){
				let bbb=inventory(spawn("SevenMilBrass",(pos.xy,pos.z+height)));
				bbb.vel.z+=1;
				bbb.amount=weaponstatus[RELS_BRASS];
				weaponstatus[RELS_BRASS]=0;
			}
			if(weaponstatus[RELS_POWDER]>0){
				let bbb=inventory(spawn("FourMilAmmo",(pos.xy,pos.z+height)));
				bbb.vel.z+=1;
				bbb.amount=weaponstatus[RELS_POWDER];
				weaponstatus[RELS_POWDER]=0;
			}

			return;
		}
		weaponstatus[RELS_BRASS]--;
		weaponstatus[RELS_POWDER]-=HDCONST_FOURFORSEVEN;
		A_StartSound("roundmaker/pop",10);

		int brek = cvar.findcvar("hdspeedrunloader_breakchance").GetInt();
		if(!random(0,brek)){
			A_SpawnItemEx("HDExplosion");
			A_Explode(32,32);
		}else A_SpawnItemEx("HDLoose7mmRecast",0,0,0,1,0,3,0,SXF_NOCHECKPOSITION);
	}
	action void A_SpeedCheckChug(bool anyotherconditions=true){
		if(
			anyotherconditions
			&&countinv("SevenMilBrass")
			&&countinv("FourMilAmmo")>=HDCONST_FOURFORSEVEN
		){
			invoker.makinground=true;

			int cap = cvar.findcvar("hdspeedrunloader_capacity").GetInt();

			//make up to [CVAR] rounds
			int counter=min(cap,countinv("SevenMilBrass"));
			invoker.weaponstatus[RELS_BRASS]=counter;
			A_TakeInventory("SevenMilBrass",counter);

			//figure out how much powder that is
			counter=min(cap*HDCONST_FOURFORSEVEN,countinv("FourMilAmmo"));
			counter-=counter%HDCONST_FOURFORSEVEN;
			invoker.weaponstatus[RELS_POWDER]=counter;
			A_TakeInventory("FourMilAmmo",counter);

			dropinventory(invoker);
		}
	}

	states {
		fire:
			TNT1 A 0 A_SpeedCheckChug();
			goto ready;
		user4:
		unload:
			TNT1 A 1 A_SpeedCheckChug(pressinguse());
			goto ready;
		spawn:
			RLDR B 35 nodelay {
				invoker.chugdelay = random(1,4);
			}
		spawn2:
			RLDR B -1 A_JumpIf(
				invoker.makinground
					&& invoker.weaponstatus[RELS_BRASS] > 0
					&& invoker.weaponstatus[RELS_POWDER] >= HDCONST_FOURFORSEVEN,
				"chug"
			);
			stop;
		chug:
			---- A 2 {
				invoker.A_Chug(); 
				invoker.chugdelay--;
			}
			---- A 0 A_JumpIf(invoker.chugdelay, "Chug");
			---- A 2 {
				invoker.A_SpeedMakeRound();
				invoker.chugdelay = random(1,4);
			}
			goto spawn2;
	}
}